config/routes.rb
Shop::Application.routes.draw do
get ":controller/:action/:name/:ActiveCode/:id"
resources :sessions,only:[:new ,:create,:destroy]
resources :users
resources :applies

root 'home#index'
get "home/about"
get "home/contact"

match '/get_activate_email', to: 'users#get_activate_email',via: 'get'
match '/get_activate_email', to: 'users#send_activate_email',via: 'post'

match '/signup', to: 'users#new',via: 'get'
match '/signin', to: 'sessions#new',via: 'get'
match '/signout', to: 'sessions#destroy',via: 'delete'
resources :products do
resources :variants
end

end

app/models/user.rb
class User < ActiveRecord::Base
before_save {self.email = email.downcase}
before_create :create_remember_token #生成记忆权标，用于记录登录状态
has_many :applies
has_many :tickets
validates :name,presence: true
validates :email,presence: true
before_save { self.email = email.downcase }

def User.new_remember_token
SecureRandom.urlsafe_base64
end

def User.encrypt(token)#加密记忆权标
Digest::SHA1.hexdigest(token.to_s)
end

private
def create_remember_token
self.remember_token = User.encrypt(User.new_remember_token)
end
has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user,only: [:edite,:update,:destroy,:index]
  before_action :correct_user,only: [:edite,:update]
  before_action :admin_user,only: [:destroy]
 # GET /users
  # GET /users.json
  def pro_activate
    set_activate
  end


  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def get_activate_email
  end

  def send_activate_email
    @user = User.find_by(email:params[:email])
    if @user && @user.IsActived == "f"
      SignupMailer.sendmail(@user).deliver
      flash[:notice] = "已经发送验证码到您邮箱，请查收"
      redirect_to root_path
    elsif @user && @user.IsActived == "t"
      flash[:notice] = "用户已经激活，请勿重复激活"
      # redirect_to :action => "new"
      redirect_to  "/get_activate_email"
    elsif @user == nil
      flash[:notice] = "用户不存在，请先注册"
      redirect_to :action => "new"
    else
      flash[:notice] = "验证码发送失败，请重试"
        redirect_to  "/get_activate_email"
    end
  end

  def create
    @user = User.new(user_params)
    @user.ActiveCode = rand(Time.now.to_i).to_s
   @user.IsActived = false
    respond_to do |format|
      if @user.save
        SignupMailer.sendmail(@user).deliver
        format.html { redirect_to @user, notice: '账号注册成功，已经发送激活码到您邮箱，请登录邮箱激活账号' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
@user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
@user = User.find(params[:id])
    @user.destroy
flash[:notice] = "账号删除成功"
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :ActiveCode,:IsActived, :department, :password,:password_confirmation, :email)
    end


    def correct_user
   @user = User.find(params[:id])
   redirect_to (root_path) unless current_user?(@user)
   end

  #  def admin_user
  #  redirect_to (root_path) unless current_user.admin?
  #  end
   def admin_user#如果不是管理员，则跳转到根页面
      @current_user = User.find_by(id: session[:user_id])
      redirect_to(root_path) unless @current_user.admin?
    end





end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <!-- <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul> -->
    </div>
  <% end %>

  <div class="field">
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :部门 %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :确认密码 %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :邮箱 %><br>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit "提交"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_activate_email.html.erb
<h1>激活账号</h1>
    <%= form_tag get_activate_email_path do |f|%>
    <p><label>邮箱：</label></p><%= text_field_tag :email%>
    <p><%= submit_tag "发送验证码"%></p>
    <p><%= link_to "还没有账号？快来注册",new_user_path%></p>
    <% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.department %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>注册</h1>

<%= render 'form' %>

<%= link_to '返回', users_path %>

app/views/users/pro_activate.html.erb
<p>激活邮件,hahah,测试一次</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<p>
  <strong>Department:</strong>
  <%= @user.department %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>