config/routes.rb
Shop::Application.routes.draw do
get ":controller/:action/:name/:ActiveCode/:id"
resources :sessions,only:[:new ,:create,:destroy]
resources :users
resources :applies

root 'home#index'
get "home/about"
get "home/contact"

match '/get_activate_email', to: 'users#get_activate_email',via: 'get'
match '/get_activate_email', to: 'users#send_activate_email',via: 'post'

match '/signup', to: 'users#new',via: 'get'
match '/signin', to: 'sessions#new',via: 'get'
match '/signout', to: 'sessions#destroy',via: 'delete'
resources :products do
resources :variants
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
  def index
remember_token = User.encrypt(cookies[:remember_token])#取出cookies中的remember_token值，加密
@current_user ||= User.find_by(remember_token: remember_token)#根据加密后的remember_token值从数据库中查找用户
  end
  def about
  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<% if @current_user %>
<h1>亲爱的<%= @current_user.name %>，欢迎来到xx领取系统</h1>
<% if current_user.admin? %>
<p>
<%= link_to "1.查看所有用户",users_path %><br>
<%= link_to "2.新建用户",new_user_path %>
<% elsif %>
<%= link_to "修改个人信息",edit_user_path(current_user)%></p>
<%= link_to "1.新建申请",new_apply_path %><br/>
<%= link_to "2.查看申请记录",applies_path %>
<% end %>
<% elsif %>
<h1>欢迎来到海那边xx领取系统</h1>
<p>
</p>
<% end %>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>