config/routes.rb
Shop::Application.routes.draw do
get ":controller/:action/:name/:ActiveCode/:id"
resources :sessions,only:[:new ,:create,:destroy]
resources :users
resources :applies

root 'home#index'
get "home/about"
get "home/contact"

match '/get_activate_email', to: 'users#get_activate_email',via: 'get'
match '/get_activate_email', to: 'users#send_activate_email',via: 'post'

match '/signup', to: 'users#new',via: 'get'
match '/signin', to: 'sessions#new',via: 'get'
match '/signout', to: 'sessions#destroy',via: 'delete'
resources :products do
resources :variants
end

end

app/models/variant.rb
class Variant < ActiveRecord::Base
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_variant, only: [:show, :edit, :update, :destroy]

  # GET /variants
  # GET /variants.json
  def index
    @variants = Variant.all
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
  end

  # GET /variants/new
  def new
    @variant = Variant.new
  end

  # GET /variants/1/edit
  def edit
  end

  # POST /variants
  # POST /variants.json
  def create
    @variant = Variant.new(variant_params)

    respond_to do |format|
      if @variant.save
        format.html { redirect_to @variant, notice: 'Variant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @variant }
      else
        format.html { render action: 'new' }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variants/1
  # PATCH/PUT /variants/1.json
  def update
    respond_to do |format|
      if @variant.update(variant_params)
        format.html { redirect_to @variant, notice: 'Variant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @variant.destroy
    respond_to do |format|
      format.html { redirect_to variants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant
      @variant = Variant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_params
      params.require(:variant).permit(:product_id, :price, :size)
    end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_for(@variant) do |f| %>
  <% if @variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% @variant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variants/edit.html.erb
<h1>Editing variant</h1>

<%= render 'form' %>

<%= link_to 'Show', @variant %> |
<%= link_to 'Back', variants_path %>

app/views/variants/index.html.erb
<h1>Listing variants</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @variants.each do |variant| %>
      <tr>
        <td><%= variant.product_id %></td>
        <td><%= variant.price %></td>
        <td><%= variant.size %></td>
        <td><%= link_to 'Show', variant %></td>
        <td><%= link_to 'Edit', edit_variant_path(variant) %></td>
        <td><%= link_to 'Destroy', variant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant', new_variant_path %>

app/views/variants/new.html.erb
<h1>New variant</h1>

<%= render 'form' %>

<%= link_to 'Back', variants_path %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @variant.product_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @variant.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @variant.size %>
</p>

<%= link_to 'Edit', edit_variant_path(@variant) %> |
<%= link_to 'Back', variants_path %>